
Import('mainenv')
env = Environment(DEBUG_BUILD = mainenv['DEBUG_BUILD'])

debugFlag = ""
if(env['DEBUG_BUILD']):
    debugFlag = "-g"

env.Append(CCFLAGS=[
    "-std=c++11",
    debugFlag,
])
env.Append(CPPPATH=[
     mainenv.baseProjectDir + "/build/include",
])
env.Append(CPPDEFINES=[
    "GLM_FORCE_RADIANS",
])
env.Append(LIBPATH=[
    mainenv.baseProjectDir + "/build/lib",
])
env.Append(LIBS=[
    "OpenDoorGL",
    "OpenDoorGL-GLFW3",
    "glfw",
    "GLEW",
])

executable = env.Program("build/LoadObjTest", "main.cpp")

targets = dict()

targets['executable'] = executable
targets['resources'] = [env.File('LoadObjTest.obj'), env.File('LoadObjTest.dds') ]

Return('targets')
