Import('testenv')
env = testenv.Clone()

debugFlag = ""
if(env['DEBUG_BUILD']):
    debugFlag = "-g"

env.Append(CCFLAGS=[
    
])
env.Append(CPPPATH=[
    
])
env.Append(CPPDEFINES=[
   
])
env.Append(LIBPATH=[
    
])
env.Append(LIBS=[
    "OpenDoorGL-GLFW3",
    "glfw",
])

executable = env.Program("build/LoadObjTest", "LoadObjTest.cpp")

targets = dict()

targets['executable'] = executable
targets['resources'] = [env.File(LoadObjTest.obj), env.File(LoadObjTest.dds), ]

Return('targets')