image: Visual Studio 2017
shallow_clone: true

install:
  - python --version
  - pip install pypiwin32

build: off
build_script:
  - cmd: scons --keep-going -Q
  - cmd: scons -c
  - cmd: scons --keep-going --debug_build -Q