image: Visual Studio 2017
shallow_clone: true

install:
  - python --version
  - pip install -U pypiwin32
  - pip install -U setuptools
  - pip install -U wheel
  - pip install -U scons

build: off
build_script:
  - cmd: scons --keep-going -Q
  - cmd: scons -c
  - cmd: scons --keep-going --debug_build -Q