stages:
  - build
  - coverage

job 1:
  stage: build
  - export DISPLAY=:0
  - scons -Q
  - scons -c 
  - scan-build-3.9 --status-bugs scons --analyze

job 2:
  stage: coverage
  script:
  - export DISPLAY=:0
  - scons --unit --test --debug_build --coverage
  - coveralls --exclude Testing --exclude Dependencies --exclude build --gcov-options '\-lp'
  