stages:
  - build
  - coverage

job 1:
  stage: build
  script:
  - scons
  - scons -c 
  - scan-build-3.9 --status-bugs scons --analyze

job 2:
  stage: coverage
  script:
  - export DISPLAY=:0
  - xhost +local:all
  - scons --debug_build --unit --test  --coverage
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_REPO_TOKEN
  - gcovr -f '.*/(Core/Source|AppFrameworks)'
  