stages:
  - build
  - coverage

job 1:
  stage: build
  script:
  - scons -Q
  - scons -c 
  - scan-build-3.9 --status-bugs scons --analyze

job 2:
  stage: coverage
  script:
  - export DISPLAY=:0
  - export CI_NAME=gitlab
  - export CI_BUILD_NUMBER="$CI_JOB_ID"
  - echo $CI_BUILD_NUMBER
  - export CI_BUILD_URL="$CI_JOB_URL"
  - echo $CI_BUILD_URL
  - export CI_BRANCH="$CI_COMMIT_REF_NAME"
  - echo $CI_BRANCH
  - export CI=true
  - xhost +local:all
  - scons --unit --test --debug_build --coverage
  - coveralls --exclude Testing --exclude Dependencies --exclude /usr --exclude build --gcov-options '\-lp'
  