
stages:
  - build
  - static_analysis
  - test
  - coverage

job 1:
  stage: build
  script: 
  - export DISPLAY=:0
  - scons -Q
  - scons -c

job 2:
  stage: static_analysis
  script:
  - export DISPLAY=:0
  - scan-build-3.9 --status-bugs scons --analyze
  - scons -c 

job 3:
  stage: test
  script:
  - export DISPLAY=:0
  - scons --unit --test --debug_build --coverage

job 4:
  stage: coverage
  script: coveralls --exclude Testing --exclude Dependencies --exclude build --gcov-options '\-lp'
  