distro: trusty
language: cpp

addons:
    apt:
      update: true

install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get -y install python3.6
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo -H python3.6 get-pip.py
  - sudo apt-get install -y git xorg-dev build-essential mesa-common-dev freeglut3-dev clang-3.9 gcovr
  - sudo -H python3.6 -m pip install -U pip
  - sudo -H python3.6 -m pip install -U setuptools
  - sudo -H python3.6 -m pip install -U wheel
  - sudo -H python3.6 -m pip install -U virtualenv
  - sudo -H python3.6 -m pip install -U cpp-coveralls
  - sudo -H python3.6 -m pip install -U gcovr
  
script:
  - python3.6 -m virtualenv venv3
  - venv3/bin/pip install -U pip
  - venv3/bin/pip install -U setuptools
  - venv3/bin/pip install -U wheel
  - venv3/bin/pip install -U scons
  - venv3/bin/scons -v
  - venv3/bin/scons -Q
  - venv3/bin/scons -c
  - scan-build-3.9 --status-bugs venv3/bin/scons --analyze
  - venv3/bin/scons -c
  - venv3/bin/scons --unit --debug_build --coverage
  
after_success:
  - python3.6 -m gcovr -e Testing -e Dependencies -e build -e usr -s -r .
# using gitlab coverage becuase of no OpenGL context in travis
#  - coveralls --exclude Testing --exclude Dependencies --exclude build --exclude usr --gcov-options '\-lp'
  
