
distro: trusty
language: cpp
install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get -y install python3.6
  - sudo apt-get install -y git cmake xorg-dev build-essential mesa-common-dev freeglut3-dev clang-3.9 gcovr
  - sudo -H python3.6 -m pip install -U pip
  - sudo -H python3.6 -m pip install -U setuptools
  - sudo -H python3.6 -m pip install -U wheel
  - sudo -H python3.6 -m pip install -U scons
  - sudo -H python3.6 -m pip install -U cpp-coveralls
  
script:
  - scons -Q
  - scons -c
  - scan-build-3.9 --status-bugs scons --analyze
  - scons -c
  - scons --unit --debug_build --coverage
  
after_success:
  - coveralls --exclude Testing --gcov-options '\-lp'
  
