
distro: trusty
language: cpp
install:
  - sudo apt-get install -y git cmake python-pip xorg-dev build-essential mesa-common-dev freeglut3-dev clang-3.9
  
script:
  - scons --keep-going --debug_build
  - scons -c
  - scons --unit -Q
  - scons -c
  - scan-build-3.9 --status-bugs scons --analyze
  
