
language: cpp
install:
  - sudo apt-get install -y git cmake python-pip xorg-dev build-essential mesa-common-dev freeglut3-dev clang-tools-6.0
  
script:
  - scons --keep-going --debug_build
  - scons -c
  - scons --unit -Q
  - scons -c
  - scan-build-6.0 --status-bugs scons --analyze
  
