distro: trusty
language: cpp

addons:
    apt:
      update: true

install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get -y install python3.6
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo -H python3.6 get-pip.py
  - sudo apt-get install -y git xorg-dev build-essential mesa-common-dev freeglut3-dev clang-3.9 gcovr
  - sudo -H python3.6 -m pip install -U pip
  - sudo -H python3.6 -m pip install -U setuptools
  - sudo -H python3.6 -m pip install -U wheel
  - sudo -H python3.6 -m pip install -U scons
  - sudo -H python3.6 -m pip install -U cpp-coveralls
  - sudo -H python3.6 -m pip install -U gcovr

script:
  - export SCONS=$(which scons)
  - /usr/bin/env python3.6 ${SCONS} -Q
  - /usr/bin/env python3.6 ${SCONS} -c
  - scan-build-3.9 --status-bugs /usr/bin/env python3.6 ${SCONS} --analyze
  - /usr/bin/env python3.6 ${SCONS} -c
  - /usr/bin/env python3.6 ${SCONS} --unit --debug_build --coverage
  
after_success:
  - python3.6 -m gcovr -e Testing -e Dependencies -e build -e usr -s -r .
# using gitlab coverage becuase of no OpenGL context in travis
#  - coveralls --exclude Testing --exclude Dependencies --exclude build --exclude usr --gcov-options '\-lp'
  
