
distro: trusty
language: cpp
install:
  - sudo apt-get install -y git cmake python-pip xorg-dev build-essential mesa-common-dev freeglut3-dev
  
script:
  - scons --keep-going -Q
  - scons -c
  - scons --keep-going --debug_build -Q
