Import('testenv')
env = testenv.Clone()
env.VariantDir('build', 'TestHeaders', duplicate=0)
debugFlag = ""
if(env['DEBUG_BUILD']):
    debugFlag = "-g"

env.Append(CCFLAGS=[
    
])
env.Append(CPPPATH=[
    
])
env.Append(CPPDEFINES=[
   
])
env.Append(LIBPATH=[
    
])
env.Append(LIBS=[
    "OpenDoorGL-GLFW3",
    "glfw",
])

test = env.CxxTest('build/test_translate', source = 'build/TranslateTest.hpp')

targets = dict()

targets['executable'] = [test]
targets['resources'] = []

Return('targets')