# This file is licensed under the MIT License.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

"""
SConcript for building the RedCube Visual test.
"""

# scons
from SCons.Script.SConscript import Return

# project
from BuildUtils import ImportVar

TEST_ENV = ImportVar('TEST_ENV')

env = TEST_ENV.Clone()

debugFlag = ""
if env['DEBUG_BUILD']:
    debugFlag = "-g"

env.Append(LIBS=[
    "OpenDoorGL-GLFW3",
    "glfw",
])

executable = env.Program("build/ButtonTest", "ButtonTest.cpp")

targets = dict()

targets['executable'] = executable
targets['resources'] = [
    env.File('ButtonTexture.bmp'), env.File('ButtonTexture.dds')]

Return('targets')
