import os

# project
import build_utils
MAIN_ENV = build_utils.ImportVar('MAIN_ENV')

testenv = Environment(DEBUG_BUILD = MAIN_ENV['DEBUG_BUILD'], 
CXXTEST=MAIN_ENV.baseProjectDir + '/Dependencies/cxxtest/bin/cxxtestgen', 
toolpath=[MAIN_ENV.baseProjectDir + '/Dependencies/cxxtest/build_tools/SCons'], 
tools = ['default','cxxtest'])

debugFlag = ""
if(testenv['DEBUG_BUILD']):
    debugFlag = "-g"

testenv.Append(CCFLAGS=[
    "-std=c++11",
    debugFlag,
])
testenv.Append(CPPPATH=[
    MAIN_ENV.baseProjectDir + "/build/include",
    MAIN_ENV.baseProjectDir + "/Testing",
    MAIN_ENV.baseProjectDir + "/Dependencies/glm",
    MAIN_ENV.baseProjectDir + "/Dependencies/cxxtest/cxxtest",
])
testenv.Append(CPPDEFINES=[
    "GLM_FORCE_RADIANS",
])
testenv.Append(LIBPATH=[
    MAIN_ENV.baseProjectDir + "/build/lib",
    
])
testenv.Append(LIBS=[
    "OpenDoorGL",
    "GLEW",
])

Export('testenv')

tests = []
for root, dirs, files in os.walk("./"):
    for file in files:
        if file.endswith("SConscript"):
            if(root == "./"):
                continue
            tests.append(SConscript(os.path.join(root, file), duplicate = 0, exports = 'MAIN_ENV'))

Return('tests')
