import os

Import('mainenv')
testenv = Environment(DEBUG_BUILD = mainenv['DEBUG_BUILD'], 
CXXTEST=mainenv.baseProjectDir + '/Dependencies/cxxtest/bin/cxxtestgen', 
toolpath=[mainenv.baseProjectDir + '/Dependencies/cxxtest/build_tools/SCons'], 
tools = ['default','cxxtest'])

debugFlag = ""
if(testenv['DEBUG_BUILD']):
    debugFlag = "-g"

testenv.Append(CCFLAGS=[
    "-std=c++11",
    debugFlag,
])
testenv.Append(CPPPATH=[
    mainenv.baseProjectDir + "/build/include",
    mainenv.baseProjectDir + "/Testing",
    mainenv.baseProjectDir + "/Dependencies/cxxtest/cxxtest",
])
testenv.Append(CPPDEFINES=[
    "GLM_FORCE_RADIANS",
])
testenv.Append(LIBPATH=[
    mainenv.baseProjectDir + "/build/lib",
    
])
testenv.Append(LIBS=[
    "OpenDoorGL",
    "GLEW",
])

Export('testenv')

tests = []
for root, dirs, files in os.walk("./"):
    for file in files:
        if file.endswith("SConscript"):
            if(root == "./"):
                continue
            tests.append(SConscript(os.path.join(root, file), duplicate = 0, exports = 'mainenv'))

Return('tests')
