

import subprocess
import platform
import os
import re

Import('mainenv')

libType = "ReleaseBuild"
debugFlag = ""
if(mainenv['DEBUG_BUILD']):
    libType = 'DebugBuild'
    debugFlag = "-g"
    

AddOption(
    '--glfw3',
    dest='glfw3',
    action='store_true',
    metavar='DIR',
    default=False,
    help='Build App using GLFW3'
)

env = Environment() 

env.Append(CPPPATH=[
    mainenv.baseProjectDir + "/AppFrameworks",
    mainenv.baseProjectDir + "/Core/Source",
    mainenv.baseProjectDir + "/build/include",
    mainenv.baseProjectDir + "/Dependencies/glm",
])

env.Append(CCFLAGS=[
    debugFlag,
])

env.Append(CXXFLAGS= [
    "-std=c++11",
])

env.Append(LINKFLAGS= [
    debugFlag,
])

env.Append(LIBPATH=[
    "/usr/lib/gnome-settings-daemon-3.0/",
    mainenv.baseProjectDir + "/Core/build",
    mainenv.baseProjectDir + "/build/lib/",
])

env.Append(LIBS=[
    "OpenDoorGL",
    "GLEW",
    "glfw",
    "GL",
    "X11",
    "Xi",
    "Xrandr",
    "Xxf86vm",
    "Xinerama",
    "Xcursor", 
    "rt",
    "m",
    "pthread",
    "dl",
])


if(GetOption('glfw3') == True):
    env.Append(GLFW3 = True)
    env.Append(CPPPATH = [
        "GLFW",
    ])
sourceFiles =  [ "GLFW/odgl_GLFW3.cpp" ]

prog = env.SharedLibrary("OpenDoorGL-GLFW3", sourceFiles)

targets = [
    prog,
    mainenv.baseProjectDir + "/AppFrameworks/odgl_WindowInterface.h",
    mainenv.baseProjectDir + "/AppFrameworks/GLFW/odgl_GLFW3.h",
]

Return('targets')
