
env = Environment()

devPath = "../../build"

env.VariantDir('build', 'Source', duplicate=0)

env.Append(CCFLAGS=[
    "-std=c++11",
])
env.Append(CPPPATH=[
     devPath + "/include",
])
env.Append(CPPDEFINES=[
    "GLM_FORCE_RADIANS",
])
env.Append(LIBPATH=[
    devPath + "/lib",
])
env.Append(LIBS=[
    "OpenDoorGL",
    "OpenDoorGL-GLFW3",

])

executable = env.Program("build/BasicCube", "build/main.cpp")

env.Install( "build", devPath + "/lib/libOpenDoorGL.so")
env.Install( "build", devPath + "/lib/libOpenDoorGL-GLFW3.so")

Return('executable')